@startuml hoge

entity user {
    + id uuid [PK]
    --
}

entity display_settings {
    + id uuid [PK]
    --
    - user_id uuid [FK]
    - body_part_id uuid [FK]
    display Boolean
}

entity body_part {
    + id uuid [PK]
    --
    name varchar(255)
}

entity body_part_tree {
    + id uuid [PK]
    --
    - ancestor_body_part_id [FK]
    - descendent_body_part_id [FK]
}

entity cracking_history {
    + id uuid [PK]
    --
    - user_id uuid [FK]
    - body_part_id uuid [FK]
    count int(2)
    register_date datetime
}

entity cracking_view {
    + id uuid [PK]
    --
    user_id uuid
    body_part_id uuid
    total_count int()
    today_count int()
     
}

user --{ display_settings
body_part -{ display_settings
body_part_tree -{ body_part
cracking_history }- user
cracking_history }-- body_part

@enduml