@startuml hoge

package domain {
    package User {
        class UserEntity {
            Id: Guid
            +GetMe()
            +Create()
        }

        interface IUserRepository {
            +GetMe()
            +Save()
        }

        class DisplaySettings {
            BodyPartId: Guid
            Display: Boolean
        }
    }

    package Cracking {
        class BodyPartEntity {
            Id: Guid
            Name: BodyPartName
            +ChangeName(BodyPartName name)
        }
        class BodyPartName {
            Value: String
        }
        class Count {
            +Value: int
        }
        class CrackingCounterEntity {
            Id: Guid
            UserId: Guid
            BodyPart: BodyPart
            TotalCount: Count
            TodayCount: Count
            Descendent:  List<CrackingCounterEntity>
        }
        class CrackingCounters {
            CrackingCounters: List<CrackingCounterEntity>
        }
        interface ICrackingCounterRepository {
            +Get(Guid id)
            +GetAll()
            +Save(CrackingCounterEntity entity)
        }
    }
    
}

package application {
    class CrackingCounterService {
            +GetCrackingCounters()
            +Register(Guid id)
            +GetHourly(DateTime day)
            +GetWeekly(DateTime startDay, DateTime endDay)
            +GetMonthly(DateTime month)
            +GetYearly(DateTime year)
            +GetTotal(Guid id)
            +GetToday(Guid id)
        }
}

package presentation {
    class RegisterViewModel {
        CrackingCounters: CrackingCounters
        +Register(Guid id)
        -UpdateList()
    }

    class DataViewModel {
        Sum: Count
        Average: Count
        DateFrom: DataDate
        DateTo: DataDate
        Datas: List<IData>
        +GetHourly()
        +GetWeekly()
        +GetMonthly()
        +GetYearly()
    }
}

UserEntity *-- DisplaySettings
UserEntity - IUserRepository
BodyPartEntity - DisplaySettings
BodyPartName - BodyPartEntity
CrackingCounterEntity - Count
CrackingCounters *-- CrackingCounterEntity
CrackingCounterEntity -- BodyPartEntity
ICrackingCounterRepository - CrackingCounterEntity
CrackingCounterService - CrackingCounters
RegisterViewModel -- CrackingCounters
RegisterViewModel -- CrackingCounterService
CrackingCounterService -- ICrackingCounterRepository
CrackingCounters -- ICrackingCounterRepository
CrackingCounterService -- CrackingCounterEntity

@enduml